services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobghar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_jobghar:/var/lib/postgresql/data

volumes:
  postgres_data_jobghar: